import {useEffect,useState,useRef} from 'react';
import {Download,MessageCircle,Bell,Timer,ShieldCheck,Sparkles,CodeXml as Github,Layers,FileText,X,ExternalLink,Code2,Radio,FlaskConical,Search} from 'lucide-react';
import {initialPortfolio} from './project-data';
type Asset={url:string;name:string;type:string};
type Project={id:string;title:string;category:string;summary:string;details:string;github:string;tags:string;status:string;assets:Asset[];demo?:boolean;subtitle?:string;version?:string;download?:string;release?:string;requirements?:string;features?:{title:string;text:string;icon:string}[];setup?:string[];installNote?:string};
type Data={name:string;headline:string;bio:string;github:string;projects:Project[]};
const initial:Data=initialPortfolio;
function safe(url:string){try{const u=new URL(url, 'https://placeholder.local');return (['https:','http:'].includes(u.protocol)||/^data:(image\/(png|jpeg|webp|gif)|video\/(mp4|webm)|application\/pdf|text\/plain);base64,/.test(url))&&(url.startsWith('data:')||url.startsWith('http')||url.startsWith('images/')||url.startsWith('./images/')||url.startsWith('data:image/'))?url:undefined;}catch{return undefined;}}
function videoEmbed(url:string){try{const u=new URL(url);let id='';if(u.hostname==='youtu.be')id=u.pathname.slice(1);else if(['www.youtube.com','youtube.com'].includes(u.hostname))id=u.searchParams.get('v')||u.pathname.split('/').pop()||'';return /^[\w-]{11}$/.test(id)?'https://www.youtube-nocookie.com/embed/'+id:null;}catch{return null;}}
export default function Portfolio(){
const [data,setData]=useState<Data>(initial),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(false),[filter,setFilter]=useState('All'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Project|null>(null);
async function load(){setLoadError(false);try{const r=await fetch('./portfolio.json',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json() as Data;setData(d);setLoaded(true);}catch{setLoadError(true);}}
useEffect(()=>{load();},[]);
useEffect(()=>{if(loaded){const id=new URLSearchParams(window.location.search).get('project');if(id)setSelected(data.projects.find(p=>p.id===id)||null);}},[loaded]);
useEffect(()=>{function key(e:KeyboardEvent){if(e.key==='Escape'){setSelected(null);}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
const dialogRef=useRef<HTMLElement>(null);
useEffect(()=>{if(!selected)return;const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialogRef.current?.querySelector<HTMLButtonElement>('button')?.focus();function trap(e:KeyboardEvent){if(e.key!=='Tab')return;const nodes=Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('a[href],button,input,video[controls],iframe')||[]);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}document.addEventListener('keydown',trap);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',trap);previous?.focus();};},[selected]);
const categories=['All',...Array.from(new Set(data.projects.map(p=>p.category)))];
const projects=data.projects.filter(p=>(filter==='All'||p.category===filter)&&[p.title,p.summary,p.tags].join(' ').toLowerCase().includes(query.toLowerCase()));
const featured=data.projects.find(p=>p.id==='hey-buddy');
const featureIcons:Record<string,any>={chat:MessageCircle,bell:Bell,focus:Timer,report:FileText,ai:Sparkles,privacy:ShieldCheck};
const picture=(p:Project)=>p.assets.find(a=>a.type.startsWith('image/')&&safe(a.url));
function art(p:Project,i:number){const img=picture(p);return <div className={'art art'+i%3}>{img?<img loading="lazy" src={safe(img.url)} alt={p.title}/>:<><div className="art-grid"/><span className="art-index">0{i+1} / {p.category.toUpperCase()}</span><div className="art-icon">{p.category==='Hardware'?<Radio/>:p.category==='Software'?<Code2/>:<FlaskConical/>}</div><span className="art-bottom">{p.demo?'EXAMPLE PROJECT':p.status.toUpperCase()}</span></>}</div>;}
return <><header><a className="brand" href="./"><span className="mark">d.</span>{data.name}<span className="brand-divider">/</span><span className="muted">workfolio</span></a><nav><a href="./#work">Selected work</a>{data.github&&<a href={safe(data.github)} target="_blank" rel="noreferrer"><Github size={17}/>GitHub</a>}</nav></header>
<main><section className="hero"><div><span className="eyebrow"><span className="tiny-square"/> THE WORK, AND THE THINKING BEHIND IT</span><h1>{data.headline.split('\n').map((s,i)=><span key={i}>{s}<br/></span>)}</h1><p>{data.bio}</p><div className="hero-actions"><a className="button primary" href="#work"><Layers size={18}/>Explore the work</a><a className="hero-source" href={safe(data.github)} target="_blank" rel="noreferrer">Built in the open <ExternalLink size={15}/></a></div><div className="hero-topics"><span>IDEAS INTO REALITY</span><span>Software</span><span>AI experiments</span><span>Open source</span></div></div><aside className="hero-note"><span className="note-symbol"><Sparkles size={64} strokeWidth={1}/></span><p>Built with curiosity.<br/>Shared with purpose.</p><div className="note-line"/><small>THE PROJECT COLLECTION</small><strong>{String(data.projects.length).padStart(2,'0')}</strong><span className="muted">projects & experiments</span></aside></section>
{loadError?<div className="alert">Projects could not be loaded. <button onClick={load}>Retry</button></div>:!loaded?<div className="loading">Loading your collection…</div>:null}
{featured&&<section className="featured-buddy" aria-label="Featured project: Hey Buddy"><div className="featured-copy"><span className="eyebrow">FEATURED PROJECT / V{featured.version}</span><h2>{featured.title}<span>{featured.subtitle}</span></h2><p>{featured.summary}</p><div className="featured-actions"><a className="button primary" href={safe(featured.download||'')}><Download size={18}/>Download for Windows</a><button className="button secondary" onClick={()=>setSelected(featured)}>Meet Buddy</button></div><small>{featured.requirements} · Installer & portable options</small><a className="featured-source" href={safe(featured.github)} target="_blank" rel="noreferrer"><Github size={16}/>Explore the source<ExternalLink size={14}/></a></div><div className="featured-image"><img src={safe(picture(featured)?.url||'')} alt="Concept illustration of a friendly desktop robot companion beside a laptop"/><span>COMPANION CONCEPT ILLUSTRATION</span></div></section>}{featured?.features&&<section className="quick-features" aria-label="Hey Buddy highlights">{featured.features.slice(0,3).map((f,i)=>{const Icon=featureIcons[f.icon]||Sparkles;return <div key={f.title}><span className="quick-number">0{i+1}</span><Icon size={24}/><h3>{f.title}</h3><p>{f.text}</p></div>;})}</section>}<section id="work" className="work"><div className="section-head"><div><span className="eyebrow">THE COLLECTION</span><h2>Selected work<span className="count">{data.projects.length}</span></h2></div><p className="muted">Explore an idea. Peek under the hood.</p></div><div className="toolbar"><div className="filters">{categories.map(c=><button key={c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><label className="search"><Search size={17}/><input aria-label="Search projects" placeholder="Find a project" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
<div className={"project-grid"+(projects.length===1?" single-project":"")}>{projects.map((p,i)=><article className="project" key={p.id}><button className="cover-button" onClick={()=>setSelected(p)} aria-label={'Explore '+p.title}>{art(p,i)}</button><div className="project-content"><div className="project-meta"><span>{p.category}</span><span>{p.demo?'Example':p.status}</span></div><button className="title-button" onClick={()=>setSelected(p)}><h3>{p.title}</h3></button><p>{p.summary}</p><div className="tags">{p.tags.split(',').filter(Boolean).map(t=><span key={t}>{t.trim()}</span>)}</div><div className="card-footer"><button onClick={()=>setSelected(p)}>Explore project</button>{p.download&&<a className="card-download" href={safe(p.download)} aria-label={'Download '+p.title}><Download size={18}/></a>}{p.github&&<a href={safe(p.github)} target="_blank" rel="noreferrer" aria-label={'GitHub source for '+p.title}><Github size={19}/></a>}</div></div></article>)}</div>{!projects.length&&<div className="empty"><Layers size={30}/><h3>{data.projects.length?'No matching projects':'Your collection starts here'}</h3><p>{data.projects.length?'Try another category or search.':'Add your first project with a summary, source link, and attachments.'}</p></div>}</section>
<footer><a className="brand" href="./"><span className="mark">d.</span>{data.name}</a><p>Always building. Always learning.</p><a href={safe(data.github)} target="_blank" rel="noreferrer">Follow the journey <ExternalLink size={14}/></a></footer></main>
{selected&&<div className="overlay" onClick={()=>setSelected(null)}><section ref={dialogRef} className="modal detail" role="dialog" aria-modal="true" aria-label={selected.title} onClick={e=>e.stopPropagation()}><button autoFocus className="close" aria-label="Close project" onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">{selected.category} / {selected.demo?'EXAMPLE':selected.status}</span><h2>{selected.title}</h2>{selected.version&&<span className="version-badge">V{selected.version} · {selected.requirements}</span>}<p className="lead">{selected.summary}</p><div className="tags">{selected.tags.split(',').filter(Boolean).map(t=><span key={t}>{t}</span>)}</div>{selected.download&&<div className="detail-actions"><a className="button primary" href={safe(selected.download)}><Download size={18}/>Download for Windows</a>{selected.release&&<a className="button secondary" href={safe(selected.release)} target="_blank" rel="noreferrer">View v{selected.version} release</a>}</div>}{picture(selected)&&<figure className="detail-cover"><img src={safe(picture(selected)!.url)} alt={picture(selected)!.name}/><figcaption>{picture(selected)!.name}</figcaption></figure>}<div className="story">{selected.details}</div>{selected.features&&<div className="feature-section"><span className="eyebrow">WHAT BUDDY BRINGS TO YOUR DAY</span><div className="feature-grid">{selected.features.map(f=>{const Icon=featureIcons[f.icon]||Sparkles;return <div className="feature-item" key={f.title}><Icon size={22}/><h3>{f.title}</h3><p>{f.text}</p></div>;})}</div></div>}{selected.setup&&<section className="setup-section"><h3>Get started with Buddy</h3><ol>{selected.setup.map(step=><li key={step}>{step}</li>)}</ol>{selected.installNote&&<p className="install-note">{selected.installNote}</p>}</section>}{selected.github&&<a className="button primary" href={safe(selected.github)} target="_blank" rel="noreferrer"><Github size={18}/>View source on GitHub</a>}{selected.assets.length>0&&<><h3 className="attachments-title">A closer look</h3><div className="attachments">{selected.assets.filter(a=>a!==picture(selected)).map((a,i)=><div className="attachment" key={i}>{a.type.startsWith('image/')?<img src={safe(a.url)} alt={a.name}/>:a.type.startsWith('video/')?(videoEmbed(a.url)?<iframe src={videoEmbed(a.url)!} title={a.name} allowFullScreen/>:<video src={safe(a.url)} controls preload="metadata"/>):null}<a href={safe(a.url)} target="_blank" rel="noreferrer"><FileText size={18}/>{a.name}<ExternalLink size={15}/></a></div>)}</div></>}{selected.demo&&<p className="demo-note">This is an example project.</p>}</section></div>}
</>;
}
